# Generated by Django 5.2.13 on 2026-04-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Candidate', 'Candidate')], max_length=20)),
                ('created_by', models.CharField(default='SYSTEM', max_length=20)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('user_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=10)),
                ('failed_attempts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
