# Generated by Django 5.2.13 on 2026-04-25 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('Word', 'Word'), ('Excel', 'Excel'), ('PPT', 'PowerPoint')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('sl_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Printed', 'Printed'), ('Deleted', 'Deleted')], default='Uploaded', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('printed_by', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
