# Generated by Django 5.2.13 on 2026-04-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bulkuploadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Staff', 'Staff'), ('Candidate', 'Candidate')], max_length=20),
        ),
    ]
