# Generated by Django 5.2.13 on 2026-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='stored_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['user', 'status'], name='file_upload_user_id_0c25dc_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_type'], name='file_upload_file_ty_ea3dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_at'], name='file_upload_uploade_d36afc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_status'], name='users_user_st_711497_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['lab'], name='users_lab_ecbf31_idx'),
        ),
    ]
